function [xGr, yGr, dGr] = ImportGrainsFromTXT(filename, dataLines)
%ImportGrainsFromTXT Import data from a text file
%  
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03-May-2022 12:42:00

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["x", "y", "d"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
xGr = tbl.x;
yGr = tbl.y;
dGr = tbl.d;
end